name: Configure executable action
description: 💥 Write your GitHub Actions using native executables!

branding:
  icon: settings
  color: yellow

inputs:
  path:
    default: .

runs:
  using: node20
  main: dist/main.js